apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: voterapp-ingress

spec:
  ingressClassName: nginx

  rules:
  - host: voterapp.local

    http:
      paths:
      - path: /

        pathType: Prefix

        backend:
          service:
            name: voterapp-service

            port:
              number: 80