name: Build and Deploy Voter App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Create Artifact
        run: zip -r voter-app.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: voter-web-app
          path: voter-app.zip